//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStoreMVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalList
    {
        public int Id { get; set; }
        public string SellerFname { get; set; }
        public string SellerLname { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public byte Status { get; set; }
        public Nullable<int> SellerId { get; set; }
        public string SellerEmail { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
